# Generated by Django 5.0.1 on 2024-01-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_logs_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Статус отправки рассылки'),
        ),
    ]
