# Generated by Django 5.0.1 on 2024-01-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_logs_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingoptions',
            name='start_time',
        ),
    ]
