# Generated by Django 5.0.1 on 2024-01-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_remove_mailingoptions_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingoptions',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала рассылки'),
        ),
    ]
