# Generated by Django 5.0.1 on 2024-01-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_mailingoptions_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingoptions',
            name='finish_time',
            field=models.DateTimeField(default=None, verbose_name='Дата окончания рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingoptions',
            name='start_time',
            field=models.DateTimeField(default=None, verbose_name='Дата начала рассылки'),
        ),
    ]
