# Generated by Django 5.0.1 on 2024-01-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0006_mailingoptions_finish_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
