# Generated by Django 5.0.1 on 2024-01-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0007_alter_client_client_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingoptions',
            options={'ordering': ['pk'], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
