# Generated by Django 5.0.1 on 2024-01-08 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0010_client_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='mailingoptions',
            name='user',
        ),
    ]
