# Generated by Django 5.0.1 on 2024-01-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0015_alter_logs_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='last_attempt_time',
            field=models.DateTimeField(verbose_name='Последняя отправка рассылки'),
        ),
    ]
