# Generated by Django 5.0.1 on 2024-01-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0016_alter_logs_last_attempt_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='send_email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='почта отправки'),
        ),
    ]
