# Generated by Django 5.0.1 on 2024-01-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0019_alter_mailingoptions_send_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingoptions',
            name='next_attempt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата следующей отправки'),
        ),
    ]
