# Generated by Django 5.0.1 on 2024-01-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0020_alter_mailingoptions_next_attempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingoptions',
            options={'ordering': ['pk'], 'permissions': [('set_active', 'Может отключать рассылки')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
